#!/usr/bin/env python3
"""Validate curriculum/seasons/*.json and generate the readable overview.

Checks: ids and episode order, level matches the season, required fields,
unique grammar ids (each concept is taught once), and that every chapter has
a full plan. Writes curriculum/overview.md and curriculum/grammar-index.md.

Usage: python3 scripts/build_curriculum.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEASONS = ROOT / "curriculum" / "seasons"
REQUIRED = ["id", "level", "title", "grammar", "theme", "key_vocab", "a_plot", "b_plot"]
LEVELS = ["A1", "A2", "B1", "B2"]


def load():
    seasons = []
    for path in sorted(SEASONS.glob("s*.json")):
        with open(path, encoding="utf-8") as f:
            seasons.append((path.name, json.load(f)))
    return seasons


def validate(seasons):
    errors = []
    seen_grammar = {}
    last_level = 0
    for name, s in seasons:
        n = s["season"]
        if name != f"s{n:02d}.json":
            errors.append(f"{name}: season number {n} doesn't match file name")
        level_idx = LEVELS.index(s["level"])
        if level_idx < last_level:
            errors.append(f"{name}: level {s['level']} goes backwards")
        last_level = level_idx
        for i, ch in enumerate(s["chapters"], start=1):
            where = f"{name} #{i}"
            missing = [k for k in REQUIRED if not ch.get(k)]
            if missing:
                errors.append(f"{where}: missing {', '.join(missing)}")
                continue
            if ch["id"] != f"s{n:02d}e{i:02d}":
                errors.append(f"{where}: id {ch['id']} out of order (expected s{n:02d}e{i:02d})")
            if ch["level"] != s["level"]:
                errors.append(f"{ch['id']}: level {ch['level']} != season level {s['level']}")
            g = ch["grammar"]
            if not re.fullmatch(r"g-[a-z0-9-]+", g.get("id", "")):
                errors.append(f"{ch['id']}: bad grammar id {g.get('id')!r}")
            elif g["id"] in seen_grammar:
                errors.append(f"{ch['id']}: grammar {g['id']} already taught in {seen_grammar[g['id']]}")
            else:
                seen_grammar[g["id"]] = ch["id"]
            for k in ("name", "scope"):
                if not g.get(k):
                    errors.append(f"{ch['id']}: grammar missing {k}")
            if not 6 <= len(ch["key_vocab"]) <= 14:
                errors.append(f"{ch['id']}: key_vocab should have 6–14 anchors, has {len(ch['key_vocab'])}")
    return errors


def md_escape(text):
    return text.replace("|", "\\|")


def write_overview(seasons):
    total = sum(len(s["chapters"]) for _, s in seasons)
    by_level = {}
    for _, s in seasons:
        by_level[s["level"]] = by_level.get(s["level"], 0) + len(s["chapters"])
    out = [
        "# Curriculum overview",
        "",
        "_Generated by `scripts/build_curriculum.py` from `curriculum/seasons/*.json`. Don't edit by hand._",
        "",
        f"**{total} chapters.** " + " · ".join(f"{lvl}: {by_level.get(lvl, 0)}" for lvl in LEVELS),
        "",
    ]
    for _, s in seasons:
        out += [
            f"## Season {s['season']}: *{s['title']['it']}* ({s['title']['en']}) · {s['level']} · {s['months']}",
            "",
            "| Ep | Title | Grammar focus | Theme | A-plot |",
            "|---|---|---|---|---|",
        ]
        for ch in s["chapters"]:
            ep = ch["id"][-2:]
            title = f"*{ch['title']['it']}*<br>{ch['title']['en']}"
            out.append(
                f"| {ep} | {md_escape(title)} | {md_escape(ch['grammar']['name'])} "
                f"| {md_escape(ch['theme'])} | {md_escape(ch['a_plot'])} |"
            )
        out.append("")
    (ROOT / "curriculum" / "overview.md").write_text("\n".join(out), encoding="utf-8")


def write_grammar_index(seasons):
    out = [
        "# Grammar index",
        "",
        "_Generated by `scripts/build_curriculum.py`. Don't edit by hand._",
        "",
        "The order in which grammar is introduced. This is the **grammar ceiling**: a chapter may use",
        "structures listed at or above its own row, and harder ones only as glossed fixed phrases.",
        "",
    ]
    for _, s in seasons:
        out += [f"## Season {s['season']} · {s['level']}", "", "| Chapter | Id | Concept | Scope |", "|---|---|---|---|"]
        for ch in s["chapters"]:
            g = ch["grammar"]
            out.append(f"| {ch['id']} | `{g['id']}` | {md_escape(g['name'])} | {md_escape(g['scope'])} |")
        out.append("")
    (ROOT / "curriculum" / "grammar-index.md").write_text("\n".join(out), encoding="utf-8")


def main():
    seasons = load()
    errors = validate(seasons)
    if errors:
        print("Curriculum errors:")
        for e in errors:
            print("  -", e)
        sys.exit(1)
    write_overview(seasons)
    write_grammar_index(seasons)
    total = sum(len(s["chapters"]) for _, s in seasons)
    print(f"OK: {len(seasons)} seasons, {total} chapters. Wrote curriculum/overview.md and curriculum/grammar-index.md")


if __name__ == "__main__":
    main()
